### ISSUE TITLE
Pipeable workflow

### ISSUE THREAD

**Issue by asiripanich** [krlmlr/mlfit#41]
@krlmlr I'm proposing that we should swap the position of the `algorithm` argument with the `fitting_problem` argument in `ml_fit()`.

```r
ml_fit <- function(fitting_problem, algorithm, ...) { ... }

fitting_problem %>%
 ml_fit(algorithm = "hipf") %>%
 ml_replicate(algorithm = "round")
```

**Comment by krlmlr** [comment]
Merged. You can add "Closes #xxx" to the pull request title to auto-close.

**Comment by asiripanich** [comment]
> 
> 
> Merged. You can add "Closes #xxx" to the pull request title to auto-close.

Will do that next time!
