### ISSUE TITLE
Add 'ml_' prefix to the main functions 

### ISSUE THREAD

**Issue by asiripanich** [krlmlr/mlfit#42]
Currently the package has three main functions `fitting_problem()`, `ml_fit()`, `ml_replicate()`. Since we will adopt a simpler name for the package, #39, should we rename `fitting_problem()` to `ml_problem()` for consistency?

**Comment by krlmlr** [comment]
I like `ml_problem()` .

**Comment by asiripanich** [comment]
This is a little more tricky to do than I thought. The scripts in `data-raw` also need to be updated and run again and `rextdata::use_extdata()` is outdated and works differently from `usethis::use_data()`. I will keep `fitting_problem()` in the pkg for now as a deprecated function.
