### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/mlfit#45]
@asiripanich: now would be a good time to run `fledge::bump_version()` .

**Comment by krlmlr** [comment]
(Don't forget to pull before doing this.)

**Comment by asiripanich** [comment]
Will bump the version to 0.4.0 in a PR that fixes #42.

**Comment by krlmlr** [comment]
Bumping works best in the main branch.

**Comment by asiripanich** [comment]
Ok, then I will bump after we merge the PR.

**Comment by asiripanich** [comment]
Closed with 6f71e7151c87551b12110d1bf8d3ec1637189bfa.
