### ISSUE TITLE
How to generate the RDS files in extdata?

### ISSUE THREAD

**Issue by asiripanich** [krlmlr/mlfit#46]
@krlmlr we need to regenerate all toy examples for #42. Could you please help me understand how did you generate them? I can't figure out where to begin. For example, `Joint-Grouped` and `Joint` which script did you use to generate them? 

Thanks!

**Comment by krlmlr** [comment]
Are the scripts in `data-raw/` any good?

**Comment by asiripanich** [comment]
I can make all other scripts work with little modifications except the `IPAF.R` which I can't figure out how you named the toy examples generated with this script in the first place. Maybe you can specify them in the `config.xml` files?
