### ISSUE TITLE
Are we ready for CRAN?

### ISSUE THREAD

**Issue by asiripanich** [krlmlr/mlfit#51]
@krlmlr we talked about checking `man` and make sure all parameters are documented. Are they anything else that you think we should do before submitting this to CRAN? Any of the outstanding issues we should address before that?

**Comment by krlmlr** [comment]
We need to add `@return` tags to the new functions you added, otherwise I think it's good.

**Comment by asiripanich** [comment]
You mean for the `int_` family in `ml-replicate.R`? 

Has `@return`:
- [ ] `ml_replicate()`
- [ ] `is.ml_fit()`
- [ ] `is.ml_problem()`
