### ISSUE TITLE
Cite Bar-Gera et al. 2009 in `ml_fit()`

### ISSUE THREAD

**Issue by asiripanich** [krlmlr/mlfit#55]
Bar-Gera, H., Konduri, K. C., Sana, B., Ye, X., & Pendyala, R. M. (2009, January). Estimating survey weights with multiple constraints using entropy optimization methods. In 88th Annual Meeting of the Transportation Research Board, Washington, DC.

**Comment by krlmlr** [comment]
Sure, we can add the citation. Are you using it in a specific context?

**Comment by asiripanich** [comment]
Isn't that the approach you use in `ml_fit_entropy_o()` ?

**Comment by krlmlr** [comment]
Right, I forgot. Thanks for catching this!
